POST   http://localhost:8080/gpapp/getCategory HTTP/1.1


### 自选
POST   http://localhost:8080/gpapp/getSelfSelect


###发送form-urlencoded数据

POST   http://192.168.1.2:8080/gpapp/getCategoryContent HTTP/1.1
Content-Type: application/x-www-form-urlencoded

pid=1

### 发送JSON数据

POST https://httpbin.org/post
Content-Type: application/json
//这里必须有一空行

{
  "query": {"a":1,"b":2}
}